# Generated by Django 5.1.2 on 2024-12-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
